//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireDepartmentApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeparturePosition
    {
        public int DeparturePositionId { get; set; }
        public int DepartureId { get; set; }
        public int PositionTypeId { get; set; }
        public System.DateTime DateTimeArrival { get; set; }
    
        public virtual Departure Departure { get; set; }
        public virtual PositionType PositionType { get; set; }
    }
}
