//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireDepartmentApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departure()
        {
            this.DepartureBurns = new HashSet<DepartureBurn>();
            this.DeparturePositions = new HashSet<DeparturePosition>();
            this.DepartureSubdivisions = new HashSet<DepartureSubdivision>();
            this.DepartureServices = new HashSet<DepartureService>();
            this.FireInfoes = new HashSet<FireInfo>();
        }
    
        public int DepartureId { get; set; }
        public System.DateTime DateTimeDepart { get; set; }
        public int DepartureAreaId { get; set; }
        public int StreetId { get; set; }
        public string NumHouse { get; set; }
        public string NumCorp { get; set; }
        public string NumAppart { get; set; }
        public string Landmark { get; set; }
        public string ApplicantPhone { get; set; }
        public string AdditionalInfo { get; set; }
        public string ExternalSignsInfo { get; set; }
        public string ExternalSignAddInfo { get; set; }
        public string ThreatPeopleInfo { get; set; }
        public Nullable<byte> ThreatPeopleCount { get; set; }
        public string ThreatPeopleAddInfo { get; set; }
        public string AffectedInfo { get; set; }
        public Nullable<byte> AffectedCount { get; set; }
        public string AffectedAddInfo { get; set; }
        public string StatePeopleInfo { get; set; }
        public string StatePeopleAddInfo { get; set; }
        public string PeopleLocationInfo { get; set; }
        public string PeopleLocationAddInfo { get; set; }
        public string ThreatFireInfo { get; set; }
        public string ThreatFireAddInfo { get; set; }
        public string NearbyObjectInfo { get; set; }
        public string NearbyObjectAddInfo { get; set; }
        public string PlaceInfo { get; set; }
        public string PlaceAddInfo { get; set; }
        public string BarrierInfo { get; set; }
        public string BarrierAddInfo { get; set; }
        public string MeetMCSInfo { get; set; }
        public string MeetMCSAddInfo { get; set; }
        public string WhyApplicantInfo { get; set; }
        public string WhyApplicantAddInfo { get; set; }
        public string FIOApplicant { get; set; }
        public bool IsFireContainment { get; set; }
        public Nullable<System.DateTime> DateTimeFireContainment { get; set; }
        public bool IsOpenBurning { get; set; }
        public Nullable<System.DateTime> DateTimeOpenBurn { get; set; }
        public bool IsAftermathFire { get; set; }
        public Nullable<System.DateTime> DateTimeAftermath { get; set; }
        public Nullable<int> FireAreaCount { get; set; }
        public Nullable<short> BarrelCount { get; set; }
    
        public virtual DepartureArea DepartureArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartureBurn> DepartureBurns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeparturePosition> DeparturePositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartureSubdivision> DepartureSubdivisions { get; set; }
        public virtual Street Street { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartureService> DepartureServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FireInfo> FireInfoes { get; set; }
    }
}
