//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireDepartmentApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FireInfoSubdivision
    {
        public int FireInfoSubdivisionId { get; set; }
        public Nullable<int> FireInfoId { get; set; }
        public Nullable<int> SubdivisionId { get; set; }
    
        public virtual FireInfo FireInfo { get; set; }
        public virtual Subdivision Subdivision { get; set; }
    }
}
