//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireDepartmentApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FireDepartEntities : DbContext
    {
        public FireDepartEntities()
            : base("name=FireDepartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlignmentFoce> AlignmentFoces { get; set; }
        public virtual DbSet<BarrelType> BarrelTypes { get; set; }
        public virtual DbSet<Broadcast> Broadcasts { get; set; }
        public virtual DbSet<BurnType> BurnTypes { get; set; }
        public virtual DbSet<CombatArea> CombatAreas { get; set; }
        public virtual DbSet<CombatDepForce> CombatDepForces { get; set; }
        public virtual DbSet<DepartureArea> DepartureAreas { get; set; }
        public virtual DbSet<DepartureBurn> DepartureBurns { get; set; }
        public virtual DbSet<DeparturePosition> DeparturePositions { get; set; }
        public virtual DbSet<Departure> Departures { get; set; }
        public virtual DbSet<DepartureService> DepartureServices { get; set; }
        public virtual DbSet<DepartureSubdivision> DepartureSubdivisions { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<FireInfo> FireInfoes { get; set; }
        public virtual DbSet<FireInfoSubdivision> FireInfoSubdivisions { get; set; }
        public virtual DbSet<MissionType> MissionTypes { get; set; }
        public virtual DbSet<PositionType> PositionTypes { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<Settlement> Settlements { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<Subdivision> Subdivisions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TechnicDivision> TechnicDivisions { get; set; }
        public virtual DbSet<Technic> Technics { get; set; }
        public virtual DbSet<WorkArea> WorkAreas { get; set; }
    }
}
