//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireDepartmentApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subdivision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subdivision()
        {
            this.DepartureSubdivisions = new HashSet<DepartureSubdivision>();
            this.FireInfoSubdivisions = new HashSet<FireInfoSubdivision>();
        }
    
        public int SubdivisionId { get; set; }
        public int DivisionId { get; set; }
        public int TechnicId { get; set; }
        public int DepartureAreaId { get; set; }
        public byte FireRank { get; set; }
    
        public virtual DepartureArea DepartureArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartureSubdivision> DepartureSubdivisions { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FireInfoSubdivision> FireInfoSubdivisions { get; set; }
        public virtual Technic Technic { get; set; }
    }
}
